### ISSUE TITLE
Error creating a new gff file

### ISSUE THREAD

**Issue by loukesio** [gencorefacility/reform#9]
Thank you for the really nice tool! 
When I am trying to merge my genomes I take this error 
```
Preparing to create new annotation file
Traceback (most recent call last):
  File "reform.py", line 426, in <module>
    main()
  File "reform.py", line 64, in main
    new_gff = create_new_gff(new_gff_name, in_arg.ref_gff, in_gff_lines, position, down_position, seq.id, len(str(record.seq)))
  File "reform.py", line 209, in create_new_gff
    gff_feat_start = int(line_elements[3])
IndexError: list index out of range
``` 

Do you have any idea why?

**Comment by mohammedkhalfan** [comment]
It looks like there is an error parsing your annotation, can you please share it so I can take a look?
